INSERT INTO CLIENTE(ID, NOME, DOC, TELEFONE, TIPO_TELEFONE, EMAIL) VALUES (1, 'CLIENTE 1', '54935200014', '40028922', 'FIXO', 'cliente.1@email.com');
INSERT INTO CLIENTE(ID, NOME, DOC, TELEFONE, TIPO_TELEFONE, EMAIL) VALUES (2, 'CLIENTE 2', '53318950009', '953552877', 'CELULAR', 'novo.cliente@email.com');

INSERT INTO ENDERECO(id, logradouro, bairro, cidade, estado_UF, ID_CLIENTE) VALUES (1, 'Rua ABC', 'Bairro ABC', 'Cidade ABC', 'SP', 1);
INSERT INTO ENDERECO(id, bairro, cidade, estado_UF, logradouro, ID_CLIENTE) VALUES (2, 'Bairro XPTO', 'Cidade XPTO', 'MG', 'Rua XPTO', 2);
INSERT INTO ENDERECO(id, bairro, cidade, estado_UF, logradouro, ID_CLIENTE) VALUES (3, 'Bairro Tal', 'Cidade Tal', 'RJ', 'Rua Tal', 1);

INSERT INTO AGENDAMENTO_ENTREGA(ID, DATA, TURNO, PEDIDO, ID_CLIENTE) VALUES(1, '20/10/2021', 'Manhã', 12445, 1);
INSERT INTO AGENDAMENTO_ENTREGA(ID, DATA, TURNO, PEDIDO, ID_CLIENTE) VALUES(2, '12/11/2021', 'Tarde', 12468, 2);
INSERT INTO AGENDAMENTO_ENTREGA(ID, DATA, TURNO, PEDIDO, ID_CLIENTE) VALUES(3, '06/01/2022', 'Manhã', 12500, 1);
INSERT INTO AGENDAMENTO_ENTREGA(ID, DATA, TURNO, PEDIDO, ID_CLIENTE) VALUES(4, '26/02/2022', 'Manhã', 12566, 1);