INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, VALOR, CATEGORIA) VALUES (1, 'Televisão', 30, 2500.00, 'Eletrônicos');
INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, VALOR, CATEGORIA) VALUES (2, 'Geladeira', 10, 3000.00, 'Eletrodomésticos');
INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, VALOR, CATEGORIA) VALUES (3, 'Batedeira', 6, 199.90, 'Eletrodomésticos');
INSERT INTO PRODUTO(ID, NOME, QUANTIDADE, VALOR, CATEGORIA) VALUES (4, 'Sofá 2 lugares', 2, 650.00, 'Móveis');